Write a migration guide with how to migrate contracts that use ByteString class
CityOfZion/neo3-boa pull request #1070
Opened 2023-06-19 16:15 UTC by meevee98

2023-06-19 16:15 UTC, lllwvlvwlll commented
Task linked: [CU-864ev3ef6 Write a migration guide with how to migrate contracts that use ByteString class](https://app.clickup.com/t/864ev3ef6)

2023-06-20 13:00 UTC, melanke requested changes

2023-06-20 13:05 UTC, luc10921 commented on docs/migration-guide.md
> +    If your contracts implement the `NEP-11` standard, be aware that Neo3Boa verifies if the methods that used to have `ByteString` type now are implemented as `Union[bytes, str]`.
> be aware that ~Neo3Boa~ **Neo3-boa** verifies

2023-06-20 13:05 UTC, luc10921 commented on docs/migration-guide.md
> +Thank you for choosing Neo3Boa, and we appreciate your cooperation in migrating to the new version.
> Thank you for choosing ~Neo3Boa~ **Neo3-boa**

2023-06-20 15:07 UTC, merged