Implement oracle commands from Neo-Express to the NeoTestRunner interface
CityOfZion/neo3-boa pull request #1097
Opened 2023-07-17 14:40 UTC by luc10921

**Summary or solution description**
Implemented the `neoxp oracle enable` and `neoxp oracle response` commands. Added new tests with responses.

**How to Reproduce**
https://github.com/CityOfZion/neo3-boa/blob/96a5d4bcb8c5038a91785b69598f4707f02aa97a/boa3_test/test_sc/native_test/oracle/OracleRequestCall.py#L1-L32

**Tests**
https://github.com/CityOfZion/neo3-boa/blob/96a5d4bcb8c5038a91785b69598f4707f02aa97a/boa3_test/tests/compiler_tests/test_native/test_oracle.py#L101-L303

**Platform:**
 - OS: Windows 10 x64
 - Python version: Python 3.7

**(Optional) Additional context**
There was a problem when using a string that had white space, instead of writing `"A string here"`, it would write `""A string here""` on the batch file.
https://github.com/CityOfZion/neo3-boa/blob/96a5d4bcb8c5038a91785b69598f4707f02aa97a/boa3_test/test_drive/neoxp/command/neoexpresscommand/neoexpresscommand.py#L33-L34

2023-07-17 14:40 UTC, lllwvlvwlll commented
Task linked: [CU-864ejer8v Implement oracle commands from Neo-Express to the NeoTestRunner interface](https://app.clickup.com/t/864ejer8v)

2023-07-17 21:14 UTC, meevee98 requested changes

2023-07-17 21:14 UTC, meevee98 commented on boa3_test/test_drive/model/network/payloads/testtransaction.py
> +                    tx._attributes.append(OracleResponse.from_json(attribute))
I think it's better to move this logic to TransactionAttribute and import there the method from the respective classes to deserialize the given json. Something like the following:

```suggestion
        if 'attributes' in json:
            tx._attributes = [TransactionAttribute.from_json(atttribute) for attribute in json['attributes']]
        else:
            tx._attributes = []
```

2023-07-17 21:14 UTC, meevee98 commented on boa3_test/test_drive/model/network/payloads/transactionattribute.py
> +        return tx_attr
Following the above suggestion
```suggestion
    @staticmethod
    def from_json(cls, json: Dict[str, Any]) -> TransactionAttribute:
        tx_type = json['type']

        if tx_type == TransactionAttributeType.ORACLE_RESPONSE:
            from boa3_test.test_drive.model.network.payloads.oracleresponse import OracleResponse
            tx_attr = OracleResponse._from_json(json)
        else:
            tx_attr = TransactionAttribute._from_json(json)

        return tx_attr
        

    @staticmethod
    def _from_json(cls, json: Dict[str, Any]) -> TransactionAttribute:
        # this one is implemented by OracleResponse
        tx_attr = TransactionAttribute(json['type'])

        return tx_attr
```

2023-07-18 18:56 UTC, meevee98 approved these changes

2023-07-18 18:56 UTC, merged