Compilation should fail with not supported feature
CityOfZion/neo3-boa pull request #1103
Opened 2023-07-20 17:46 UTC by meevee98

**Summary or solution description**
List comprehension is not supported, but the compiler doesn't raise any errors when it is used in a smart contract script.
Changed to raise compiler error when list comprehension is used. It's going to be implemented in future tasks.

**How to Reproduce**
https://github.com/CityOfZion/neo3-boa/blob/3d257251d5991ac2c5c9f45d226d9181f0f3c928/boa3_test/test_sc/list_test/ListComprehensionStr.py#L4-L7

**Tests**
https://github.com/CityOfZion/neo3-boa/blob/3d257251d5991ac2c5c9f45d226d9181f0f3c928/boa3_test/tests/compiler_tests/test_list.py#L2107-L2112

**Platform:**
 - OS: Windows 10 x64
 - Python version: Python 3.7+

2023-07-20 17:46 UTC, lllwvlvwlll commented
Task linked: [CU-861n2rz03 list comprehension is not returning correct type](https://app.clickup.com/t/861n2rz03)

2023-07-20 18:41 UTC, luc10921 approved these changes

2023-07-21 07:28 UTC, ixje requested changes
The error I see is
> The following operation is not supported: 'comprehension' ...

Can we call it `list comprehension` to be explicit? I don't know if just `comprehension` is going to be enough for the end user to understand the error.

2023-07-21 14:59 UTC, ixje approved these changes

2023-07-24 12:22 UTC, merged