Incorrect code generation of static variables
CityOfZion/neo3-boa pull request #1106
Opened 2023-07-25 19:28 UTC by meevee98

2023-07-25 19:28 UTC, lllwvlvwlll commented
Task linked: [CU-861n3mtht incorrect code generation](https://app.clickup.com/t/861n3mtht)

2023-07-26 07:02 UTC, ixje requested changes
The generated code is still incorrect. See Clickup for a new package with instructions how you can test it yourself against the contract that produces the error

2023-07-26 15:10 UTC, ixje approved these changes

2023-07-27 12:21 UTC, luc10921 approved these changes

2023-07-27 12:21 UTC, merged