CU-2ewetjc - Add support to string.replace method
CityOfZion/neo3-boa pull request #1146
Opened 2023-11-01 02:23 UTC by jplippi

2023-11-01 02:23 UTC, lllwvlvwlll commented
Task linked: [CU-2ewetjc Add support to string.replace method](https://app.clickup.com/t/2ewetjc)

2023-11-01 02:23 UTC, lllwvlvwlll commented
Task linked: [CU-2ewetjc Add support to string.replace method](https://app.clickup.com/t/2ewetjc)

2023-11-06 12:27 UTC, luc10921 requested changes

2023-11-06 12:27 UTC, luc10921 commented on boa3/internal/model/builtin/classmethod/replacemethod.py
> +            self_type = Type.bytes
Since `self_type` is an `IByteStringType` it would be nice to have `bytes` tests too, not just `str` tests.

2023-11-13 19:43 UTC, merged