Check and do something about all "TODO" comments in code
CityOfZion/neo3-boa pull request #1148
Opened 2023-11-10 17:29 UTC by luc10921

**Summary or solution description**

2023-11-10 17:29 UTC, lllwvlvwlll commented
Task linked: [CU-864ec9c4g Check and do something about all "TODO" comments in code](https://app.clickup.com/t/864ec9c4g)

2023-11-16 22:19 UTC, meevee98 requested changes

2023-11-16 22:19 UTC, meevee98 commented on boa3_test/test_drive/model/network/payloads/signer.py
> +        # TODO: implement allowed witness rules #86a1cu3y6
We won't work on this, you can remove this TODO

2023-11-16 22:19 UTC, meevee98 commented on boa3_test/test_drive/model/network/payloads/signer.py
> +        # TODO: implement allowed witness rules #86a1cu3y6
We won't work on this, you can remove this TODO

2023-11-16 22:19 UTC, meevee98 commented on boa3/internal/analyser/importanalyser.py
> +                # TODO: only user modules and typing lib imports are implemented #86a1ct917
We won't work on this, you can remove this TODO

2023-11-21 22:30 UTC, meevee98 approved these changes

2023-11-21 22:31 UTC, merged