CU-86drpncjw - Refactor example_tests/test_htlc.py to use BoaConstructor
CityOfZion/neo3-boa pull request #1227
Opened 2024-03-21 19:28 UTC by luc10921

Refactored `example_tests/test_htlc.py` files to use `BoaTestCase `in place of `BoaTest `for unit testing.

2024-03-21 19:28 UTC, melanke commented
Task linked: [CU-86drpncjw Refactor example_tests/test_htlc.py to use BoaConstructor](https://app.clickup.com/t/86drpncjw)

2024-03-25 17:56 UTC, meevee98 requested changes

2024-03-25 17:56 UTC, meevee98 commented on boa3_test/tests/examples_tests/test_htlc.py
> +        self.assertEqual(transferred_amount_gas, filtered_transfer_events[1].amount)
when there's more than one event expected, you should use variables to  let the test more readable
```suggestion
        refund_A, refund_B = filtered_transfer_events
        
        self.assertEqual(htlc, refund_A.source)
        self.assertEqual(person_a, refund_A.destination)
        self.assertEqual(transferred_amount_neo, refund_A.amount)

        self.assertEqual(htlc, refund_B.source)
        self.assertEqual(person_b, refund_B.destination)
        self.assertEqual(transferred_amount_gas, refund_B.amount)
```

2024-03-25 17:56 UTC, meevee98 commented on boa3_test/tests/examples_tests/test_htlc.py
> +        await asyncio.sleep(self.REFUND_WAIT_TIME)
it seems that all `asyncio.sleep` calls in the test case use the same arguments, so you can move it to a helper method call.
```python
async def wait_refund_time():
    return await asyncio.slepp(self.REFUND_WAIT_TIME)
```

2024-03-25 20:10 UTC, merged