CU-86dtu8tcn - Add boa test constructor to the documentation
CityOfZion/neo3-boa pull request #1265
Opened 2024-06-17 21:04 UTC by luc10921

2024-06-17 21:04 UTC, melanke commented
Task linked: [CU-86dtu8tcn Add boa test constructor to the documentation](https://app.clickup.com/t/86dtu8tcn)

2024-06-18 22:20 UTC, meevee98 requested changes

2024-06-18 22:20 UTC, meevee98 commented on docs/source/testing-and-debugging.md
> +will be installed too.
It is worth mentioning that the packages can be installed directly when neo3-boa is installed by using `pip install neo3-boa[test]`

2024-06-18 22:20 UTC, meevee98 commented on docs/source/testing-and-debugging.md
> +contract, use the `call` method from `SmartContractTestCase`. The two positional parameters are the name of the method
the user reading this documentation may not know the difference between invoke and test invoke, you can just write "To invoke your smart contract [...]" here

2024-06-18 22:20 UTC, meevee98 commented on docs/source/testing-and-debugging.md
> +you want to invoke and a list of its arguments. The keyword parameters are the return type, a list of signing accounts,
ensure that methodName, args and returnType are mandatory

2024-06-18 22:20 UTC, meevee98 commented on docs/source/testing-and-debugging.md
> +test invoke but also define the signers of the transaction.
we are not going to explain what signers and witnesses scopes are in this file, can you link the neo documentation related to signers here to guide the user if it wants more information?

2024-06-18 22:20 UTC, meevee98 commented on docs/source/testing-and-debugging.md
> +        cls.contract_hash = await cls.deploy("./smart_contract.nef", cls.genesis)
I think these code snippets should be along the texts that explain what to do, the text by itself does not help much without code to look into
If the user if following the documentation I don't think its test is going to look like this as the text before it suggests, there is mention to initiating accounts, but is not explicit that in this tutorial we're setting a user test account.

2024-06-18 22:20 UTC, meevee98 commented on docs/source/testing-and-debugging.md
> +        cls.contract_hash = await cls.deploy("./smart_contract.nef", cls.genesis)
It's worth mentioning that the test case run on a local chain that is going to reset each time the tests are executed, that's why the contract needs to be deployed and the user balance needs to me initialized

2024-06-18 22:20 UTC, meevee98 commented on docs/source/testing-and-debugging.md
> +        cls.user1 = cls.node.wallet.account_new("123", "alice")
just for clarity sake, i think it's better to put the label first
```suggestion
        cls.user1 = cls.node.wallet.account_new(label="alice", password="123")
```

2024-06-18 22:20 UTC, meevee98 commented on docs/source/testing-and-debugging.md
> +        # you can name the account whatever you want, but the password needs to be "123"
is there a reason that the password needs to be "123"? is it a boa-test-case issue?

2024-06-18 22:20 UTC, meevee98 commented on docs/source/testing-and-debugging.md
> +selecting your "main" smart contract, and transferring GAS to the new accounts.
it is worth mentioning why the tests must be async:
the tests use a local chain to run the invocations and the communication with the chain is asynchronous, so anything that needs to interact with it (deploy, token transfers, vote, etc) must be awaited

2024-06-19 14:45 UTC, meevee98 approved these changes

2024-06-19 14:45 UTC, merged