CU-86dtu92vq - Include how to test smart contract events using boa test constructor
CityOfZion/neo3-boa pull request #1268
Opened 2024-06-19 17:25 UTC by luc10921

2024-06-19 17:25 UTC, melanke commented
Task linked: [CU-86dtu92vq Include how to test smart contract events using boa test constructor](https://app.clickup.com/t/86dtu92vq)

2024-06-19 22:51 UTC, meevee98 requested changes

2024-06-19 22:51 UTC, meevee98 commented on docs/source/testing-and-debugging.md
> +implementation for reference.
Regarding creating new classes to handle other events, I think it's better to give an example in this file than to just link to the boaconstructor code.
Can you change it to create a class to handle the same Nep17 event? But include a validation for `from` or `to` being None (doesn't need to explain)

2024-06-20 14:16 UTC, meevee98 approved these changes

2024-06-20 14:16 UTC, merged